// ============================================================
// SERVER.JS - ISSUEFORGE BACKEND - PHASE 2
// Express server with MongoDB integration and full CRUD API
// ============================================================

// Load environment variables from .env file
require("dotenv").config();

const express = require("express");
const cors = require("cors");
const mongoose = require("mongoose");

// Initialize Express app
const app = express();
const PORT = process.env.PORT || 5000;

// ============================================================
// MIDDLEWARE
// ============================================================

// Enable CORS to allow frontend (React) to connect from a different port
app.use(cors());

// Parse JSON request bodies
app.use(express.json());

// Log all incoming requests
app.use((req, res, next) => {
  console.log(`${new Date().toISOString()} - ${req.method} ${req.url}`);
  next();
});

// ============================================================
// MONGODB CONNECTION
// ============================================================

// Get MongoDB URI from environment variable
const MONGODB_URI = process.env.MONGODB_URI;

if (!MONGODB_URI) {
  console.error(
    "❌ ERROR: MONGODB_URI is not defined in environment variables"
  );
  console.error(
    "Please create a .env file with MONGODB_URI=your_connection_string"
  );
  process.exit(1);
}

// Connect to MongoDB
mongoose
  .connect(MONGODB_URI)
  .then(() => {
    console.log("✅ Successfully connected to MongoDB");
    console.log(`📊 Database: ${mongoose.connection.name}`);
  })
  .catch((error) => {
    console.error("❌ MongoDB connection error:", error.message);
    console.error("Please check your MONGODB_URI in .env file");
    process.exit(1);
  });

// Handle MongoDB connection events
mongoose.connection.on("disconnected", () => {
  console.log("⚠️  MongoDB disconnected");
});

mongoose.connection.on("error", (error) => {
  console.error("❌ MongoDB error:", error.message);
});

// ============================================================
// MONGOOSE SCHEMA & MODEL
// ============================================================

const issueSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: [true, "Title is required"],
      trim: true,
    },
    owner: {
      type: String,
      required: [true, "Owner is required"],
      trim: true,
    },
    status: {
      type: String,
      enum: ["New", "In Progress", "Fixed", "Closed"],
      default: "New",
    },
    created: {
      type: Date,
      default: Date.now,
    },
    effort: {
      type: Number,
      min: 0,
      default: 0,
    },
    dueDate: {
      type: Date,
      default: null,
    },
  },
  {
    timestamps: true, // Adds createdAt and updatedAt fields
  }
);

// Create Issue model
const Issue = mongoose.model("Issue", issueSchema);

// ============================================================
// API ROUTES - FULL CRUD OPERATIONS
// ============================================================

// GET /api/issues - Fetch all issues from database
app.get("/api/issues", async (req, res) => {
  try {
    console.log("📋 Fetching all issues from database...");

    // Fetch all issues, sorted by creation date (newest first)
    const issues = await Issue.find().sort({ created: -1 });

    console.log(`✅ Found ${issues.length} issues`);
    res.json(issues);
  } catch (error) {
    console.error("❌ Error fetching issues:", error.message);
    res.status(500).json({
      error: "Failed to fetch issues",
      message: error.message,
    });
  }
});

// POST /api/issues - Create a new issue
app.post("/api/issues", async (req, res) => {
  try {
    console.log("➕ Creating new issue:", req.body);

    // Validate required fields
    if (!req.body.title || !req.body.owner) {
      return res.status(400).json({
        error: "Validation failed",
        message: "Title and Owner are required fields",
      });
    }

    // Create new issue from request body
    const newIssue = new Issue({
      title: req.body.title,
      owner: req.body.owner,
      status: req.body.status || "New",
      effort: req.body.effort || 0,
      dueDate: req.body.dueDate || null,
      // created field will be auto-generated by default
    });

    // Save to database
    const savedIssue = await newIssue.save();

    console.log(`✅ Issue created with ID: ${savedIssue._id}`);
    res.status(201).json(savedIssue);
  } catch (error) {
    console.error("❌ Error creating issue:", error.message);
    res.status(500).json({
      error: "Failed to create issue",
      message: error.message,
    });
  }
});

// PUT /api/issues/:id - Update an existing issue
app.put("/api/issues/:id", async (req, res) => {
  try {
    const issueId = req.params.id;
    console.log(`📝 Updating issue ${issueId}:`, req.body);

    // Validate MongoDB ObjectId format
    if (!mongoose.Types.ObjectId.isValid(issueId)) {
      return res.status(400).json({
        error: "Invalid ID format",
        message: "The provided ID is not a valid MongoDB ObjectId",
      });
    }

    // Find and update the issue
    // { new: true } returns the updated document
    // { runValidators: true } runs schema validation on update
    const updatedIssue = await Issue.findByIdAndUpdate(
      issueId,
      {
        title: req.body.title,
        owner: req.body.owner,
        status: req.body.status,
        effort: req.body.effort,
        dueDate: req.body.dueDate,
      },
      { new: true, runValidators: true }
    );

    // Check if issue was found
    if (!updatedIssue) {
      return res.status(404).json({
        error: "Issue not found",
        message: `No issue found with ID: ${issueId}`,
      });
    }

    console.log(`✅ Issue ${issueId} updated successfully`);
    res.json(updatedIssue);
  } catch (error) {
    console.error("❌ Error updating issue:", error.message);
    res.status(500).json({
      error: "Failed to update issue",
      message: error.message,
    });
  }
});

// DELETE /api/issues/:id - Delete an issue
app.delete("/api/issues/:id", async (req, res) => {
  try {
    const issueId = req.params.id;
    console.log(`🗑️  Deleting issue ${issueId}...`);

    // Validate MongoDB ObjectId format
    if (!mongoose.Types.ObjectId.isValid(issueId)) {
      return res.status(400).json({
        error: "Invalid ID format",
        message: "The provided ID is not a valid MongoDB ObjectId",
      });
    }

    // Find and delete the issue
    const deletedIssue = await Issue.findByIdAndDelete(issueId);

    // Check if issue was found
    if (!deletedIssue) {
      return res.status(404).json({
        error: "Issue not found",
        message: `No issue found with ID: ${issueId}`,
      });
    }

    console.log(`✅ Issue ${issueId} deleted successfully`);
    res.json({
      message: "Issue deleted successfully",
      deletedIssue,
    });
  } catch (error) {
    console.error("❌ Error deleting issue:", error.message);
    res.status(500).json({
      error: "Failed to delete issue",
      message: error.message,
    });
  }
});

// Root endpoint - API documentation
app.get("/", (req, res) => {
  res.json({
    message: "🔥 IssueForge API - Phase 2",
    version: "2.0",
    database: "MongoDB",
    endpoints: [
      "GET /api/issues - Get all issues",
      "POST /api/issues - Create new issue",
      "PUT /api/issues/:id - Update issue by ID",
      "DELETE /api/issues/:id - Delete issue by ID",
    ],
  });
});

// ============================================================
// START SERVER
// ============================================================

app.listen(PORT, () => {
  console.log("=".repeat(50));
  console.log("🔥 IssueForge Backend Server - Phase 2");
  console.log("=".repeat(50));
  console.log(`✅ Server is running on http://localhost:${PORT}`);
  console.log(`📡 API endpoint: http://localhost:${PORT}/api/issues`);
  console.log("=".repeat(50));
  console.log("Waiting for requests...\n");
});

// Handle graceful shutdown
process.on("SIGINT", async () => {
  console.log("\n👋 Shutting down server gracefully...");
  await mongoose.connection.close();
  console.log("✅ MongoDB connection closed");
  process.exit(0);
});
